-- Stage 2: tag every company-owned record with a workspaceId and backfill all
-- existing rows into the Default Workspace so nothing breaks.
ALTER TABLE "Project" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "LedgerEntry" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ExpenseCategory" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "DailyLog" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "PunchItem" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Subscription" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "BillingInvoice" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ChangeOrder" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ChangeOrderActivity" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Commitment" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Document" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Bid" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Inspection" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "SafetyIncident" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Equipment" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ChecklistTemplate" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Checklist" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "DrawingVersion" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "PlanMarkup" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ScheduledReport" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Attendance" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Observation" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "CoordinationIssue" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ActionPlan" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Correspondence" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "WorkTask" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "ScheduleItem" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Crew" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "DirectoryContact" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "CompanyDoc" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Announcement" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "FormTemplate" ADD COLUMN "workspaceId" TEXT;
ALTER TABLE "Conversation" ADD COLUMN "workspaceId" TEXT;

UPDATE "Project" SET "workspaceId" = 'ws_default';
UPDATE "LedgerEntry" SET "workspaceId" = 'ws_default';
UPDATE "ExpenseCategory" SET "workspaceId" = 'ws_default';
UPDATE "DailyLog" SET "workspaceId" = 'ws_default';
UPDATE "PunchItem" SET "workspaceId" = 'ws_default';
UPDATE "Subscription" SET "workspaceId" = 'ws_default';
UPDATE "BillingInvoice" SET "workspaceId" = 'ws_default';
UPDATE "ChangeOrder" SET "workspaceId" = 'ws_default';
UPDATE "ChangeOrderActivity" SET "workspaceId" = 'ws_default';
UPDATE "Commitment" SET "workspaceId" = 'ws_default';
UPDATE "Document" SET "workspaceId" = 'ws_default';
UPDATE "Bid" SET "workspaceId" = 'ws_default';
UPDATE "Invoice" SET "workspaceId" = 'ws_default';
UPDATE "Inspection" SET "workspaceId" = 'ws_default';
UPDATE "SafetyIncident" SET "workspaceId" = 'ws_default';
UPDATE "Equipment" SET "workspaceId" = 'ws_default';
UPDATE "ChecklistTemplate" SET "workspaceId" = 'ws_default';
UPDATE "Checklist" SET "workspaceId" = 'ws_default';
UPDATE "DrawingVersion" SET "workspaceId" = 'ws_default';
UPDATE "PlanMarkup" SET "workspaceId" = 'ws_default';
UPDATE "ScheduledReport" SET "workspaceId" = 'ws_default';
UPDATE "Attendance" SET "workspaceId" = 'ws_default';
UPDATE "Observation" SET "workspaceId" = 'ws_default';
UPDATE "CoordinationIssue" SET "workspaceId" = 'ws_default';
UPDATE "ActionPlan" SET "workspaceId" = 'ws_default';
UPDATE "Correspondence" SET "workspaceId" = 'ws_default';
UPDATE "WorkTask" SET "workspaceId" = 'ws_default';
UPDATE "ScheduleItem" SET "workspaceId" = 'ws_default';
UPDATE "Crew" SET "workspaceId" = 'ws_default';
UPDATE "DirectoryContact" SET "workspaceId" = 'ws_default';
UPDATE "CompanyDoc" SET "workspaceId" = 'ws_default';
UPDATE "Announcement" SET "workspaceId" = 'ws_default';
UPDATE "FormTemplate" SET "workspaceId" = 'ws_default';
UPDATE "Conversation" SET "workspaceId" = 'ws_default';
